---
- name: Playbook to deploy sp-test
  vars:
    terraform_template_vars: "{{ playbook_dir }}/group_vars/terraform.template.tfvars"
    credentials_template_vars: "{{ playbook_dir }}/group_vars/credentials.auto.template.tfvars"
    shared_outputs_vars: "{{ playbook_dir }}/group_vars/shared_outputs.json"
    shared_outputs_template: "{{ playbook_dir }}/shared_outputs_template.j2" 
  hosts: localhost
  pre_tasks:
    - name: Create shared outputs file if doesn't exist
      copy:
        dest: "{{ shared_outputs_vars }}"
        force: false
        content: {}
      check_mode: no
  roles:
    - role: 101-azure-vnet-std
    - role: 105-azure-ocp-ipi
    - role: 150-azure-storage-blob
    - role: 230-integration-mq